Fixed incorrect injection of product tracing serivce
Laixer/FunderMaps pull request #281
Opened 2020-09-15 11:29 UTC by tabeckers

**What issue does this PR address?**
#278 

**Does this PR introduce a breaking change?**
No.

**Other information**:
-

2020-09-15 11:47 UTC, yorickdewid requested changes
Is there any way we can add a regression test?

2020-09-15 12:41 UTC, tabeckers commented
We could, but this would work best using a mock database or the database itself in some way. We have to verify that this service actually updates the entries in the database. At the moment, if it's unable to do so, an npgsql exception is raised (similar to other database operation failures). For now I think this is sufficient.

At the moment I think this is too complex for this release. I've made an issue for this, because this part of our core is crucial (#282).

2020-09-17 08:30 UTC, tabeckers commented
Upon further discussion, a regression test will be added for the dependency injector #282.

2020-09-17 13:01 UTC, yorickdewid approved these changes

2020-09-17 13:01 UTC, merged