Implement recovery features
Laixer/FunderMaps pull request #480
Opened 2021-02-16 16:39 UTC by pnobbe

Includes updated postman collection

### Merge when:

* [ ] The merge build succeeded
* [ ] The PR has been reviewed and is approved
* [ ] All packages are upgraded to the latest version (only PR into master)

**What issue does this PR address?**

Implements the necessary recovery features for the upcoming client app feature upgrade.

**Does this PR introduce a breaking change?**

No

**Additional information**:

Remove branch after merge

2021-02-16 21:11 UTC, yorickdewid requested changes
* `IRecoverySampleRepository` warnings/errors need to addressed somehow. The build in `develop` must never report warnings/errors.
* About consistency; Even if some things are wrong or could be done better, abstain and submit as isolated patch. This makes reviews much easier and keeps a linear record of changes.

Postman file is ignored in the review

2021-02-16 21:16 UTC, yorickdewid commented
Inquiry entities are subject to state control in which they can only move from one state (say 'pending') to another state ('pending_review'). This mechanism also applies to recoveries and is lacking. Account for this

2021-02-24 14:04 UTC, pnobbe commented
Rebased from `develop`

2021-02-25 15:34 UTC, yorickdewid requested changes

2021-02-25 15:34 UTC, yorickdewid commented on src/FunderMaps.WebApi/Controllers/Report/RecoveryController.cs
> +
Remove empty line

2021-02-25 15:34 UTC, yorickdewid commented on src/FunderMaps.WebApi/Controllers/Report/RecoveryController.cs
> +
Remove empty line

2021-02-25 15:37 UTC, yorickdewid approved these changes

2021-02-25 15:39 UTC, merged